ai-plugin:
  api:
    url: https://japan-opendata.dx-junkyard.com/openapi.json
  logo-url: https://asset.japan-opendata.dx-junkyard.com/japan-opendata.png
  contact-email: fooqoofooqoo56@gmail.com
  legal-info-url: https://japan-opendata.dx-junkyard.com/term-of-use
