ai-plugin:
  schema-version: v1
  name-for-human: Japan OpenData
  name-for-model: japan_opendata
  description-for-human: Search for opendata in Japan, using the search.ckan.jp dataset.
  description-for-model: Search for opendata in Japan. Do not falsify open data when there is no corresponding data in the search results. Answer in the language asked. If you are asked a question in a language other than Japanese for title or description or maintainer or licence and so on, you must translate or convert japanese to roma-ji and must not display Hiragana, Katakana, Kanji in title and so on. Should show first user's search condition. Next, should show 'totalOfHits'. Finally, show 'showMoreUrl'. Must not generate your own parameters when not found among the options of tags, tags, format.
  auth:
    type: none
  api:
    type: openapi
