ai-plugin:
  schema-version: v1
  name-for-human: Japan OpenData
  name-for-model: japan_opendata
  description-for-human: Search for opendata in Japan, using the search.ckan.jp dataset.
  description-for-model: Search for opendata in Japan. Do not falsify open data when there is no corresponding data in the search results. Should use titleEnglish of response instead of title if asked in non-Japanese. Answer in the language asked. If you ask a question in a language other than Japanese, you must translate it into the language asking and not display Hiragana, Katakata, or Kanji. Should show first user's search condition. Next, should show 'searchResultInfo.totalOfHits'. Finally, show 'showMoreUrl'. Must not generate your own parameters when not found among the options of organization, category, format.
  auth:
    type: none
  api:
    type: openapi
